spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB



#mybatis
mybatis:
  type-aliases-package: usyd.mingyi.animalcare.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml



