spring:
  datasource:
    username: root
    password: LMY741917776!
    #url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://mysql:3306/db01?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://35.244.84.188:3306/db01?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    port: 587
    host: smtp.gmail.com
    username: LMY741917776@gmail.com
    password: qybmnkrzlrfnxlzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB



#mybatis
mybatis:
  type-aliases-package: usyd.mingyi.animalcare.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml



