version: "3"

services:
  animalCareSerivce:
    image: mingyi_docker:1.0
    container_name: acs01
    ports:
      - "8080:8080"
    volumes:
      - /app/animalCareSerivce:/data
    networks:
      - mingyi_net
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'db01'
      MYSQL_USER: 'lmy'
      MYSQL_PASSWORD: 'lmy520'
    ports:
      - "3306:3306"
    volumes:
      - /app/mysql/db:/var/lib/mysql
      - /app/mysql/conf/my.cnf:/etc/my.cnf
      - /app/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mingyi_net
    command: --default-authentication-plugin=mysql_native_password
networks:
  mingyi_net:
